package sshConfig

// SSHConfigurationEntry represents the data which can be used to generate an
// SSH Configuration File Entry.
type SSHConfigurationEntry struct {
	AddressFamily                   string
	BatchMode                       string
	BindAddress                     string
	ChallengeResponseAuthentication string
	CheckHostIP                     string
	Cipher                          string
	Ciphers                         string
	ClearAllForwardings             string
	Compression                     string
	CompressionLevel                int
	ConnectionAttempts              int
	ConnectTimeout                  int
	ControlMaster                   string
	ControlPath                     string
	DynamicForward                  string
	EnableSSHKeysign                string
	EscapeChar                      string
	ExitOnForwardFailure            string
	ForwardAgent                    string
	ForwardX11                      string
	ForwardX11Trusted               string
	GatewayPorts                    string
	GSSAPIAuthentication            string
	GSSAPIKeyExchange               string
	GSSAPIClientIdentity            string
	GSSAPIDelegateCredentials       string
	GSSAPIRenewalForcesRekey        string
	GSSAPITrustDNS                  string
	HashKnownHosts                  string
	Host                            string
	HostbasedAuthentication         string
	HostKeyAlgorithms               string
	HostKeyAlias                    string
	HostName                        string
	IdentitiesOnly                  string
	IdentityFile                    string
	KBDInteractiveAuthentication    string
	KBDInteractiveDevices           string
	LocalCommand                    string
	LocalForward                    string
	LogLevel                        string
	MACs                            string
	NumberOfPasswordPrompts         int
	PasswordAuthentication          string
	PermitLocalCommand              string
	Port                            int
	PreferredAuthentications        string
	Protocol                        string
	ProxyCommand                    string
	RekeyLimit                      string
	RemoteForward                   string
	RhostsRSAAuthentication         string
	RSAAuthentication               string
	SendEnv                         string
	ServerAliveCountMax             int
	ServerAliveInterval             int
	SmartcardDevice                 string
	StrictHostKeyChecking           string
	TCPKeepAlive                    string
	Tunnel                          string
	TunnelDevice                    string
	UsePrivilegedPort               string
	User                            string
	UserKnownHostsFile              string
	VerifyHostKeyDNS                string
	VisualHostKey                   string
	XAuthLocation                   string
}
